// v0.1.0

package test

import "github.com/pkg/errors"

var (
	// ErrMock is the error generated by the mocked readers and writers
	ErrMock = errors.New("tis is an error voluntarily generated")
)

// FaultyReader implements the io.Reader interface but fails when used.
type FaultyReader struct {
}

// Read fails systematically.
func (fr FaultyReader) Read(p []byte) (n int, err error) {
	return 0, ErrMock
}
