// v0.2.1
// Author: DIEHL E.
// (C) Sony Pictures Entertainment, Mar 2021

package test

import "github.com/pkg/errors"

var (
	// ErrMock is the error generated by the mocked readers and writers
	ErrMock = errors.New("this is an error voluntarily generated")
)

// FaultyReader implements the io.ReadCloser interface but fails when used.
type FaultyReader struct {
}

// Read fails systematically.
func (fr FaultyReader) Read(p []byte) (n int, err error) {
	return 0, ErrMock
}

// Close fails systematically.
func (fr FaultyReader) Close() error {
	return ErrMock
}
